### ISSUE TITLE
Reflection Problem

### ISSUE THREAD

**Issue by hiimtmac** [SwifQL/SwifQL#20]
Given this model:
```swift
public struct T: Codable, Reflectable, Tableable {
    let name: String
    let rate: Double

    enum CodingKeys: String, CodingKey {
        case name
        case rate
    }

    public init(from decoder: Decoder) throws {
        self.name = try container.decode(String.self, forKey: .name)
        self.rate = try container.decodeIfPresent(Double.self, forKey: .rate) ?? 0.0
    }
}
```

If one of the properties in the `init(decoder:)` method is optionally decoded and provided a default value like `rate` above, when you try and access it in your query:
```swift
let t = T.as("t")
t~\.rate // is NOT "rate"

or

\T.rate // is NOT "rate"
```
Normal optionals work fine (`try container.decodeIfPresent(Double.self, forKey: .rate)`) but as soon as you add the default value (`?? 0.0`) it does not work.

Any idea why this might be or am I doing something wrong?

[Failing Test](https://github.com/hiimtmac/SwifQLBug/blob/fe8749c43482b8daf32a8834e5f6249ce7dd18b0/Tests/SwifQLBugTests/SwifQLBugTests.swift#L24) | [Example repo](https://github.com/hiimtmac/SwifQLBug)

**Comment by MihaelIsaev** [comment]
As far as I can see you are using it with NIO2, so it means that with Vapor 4 - is it correct?

**Comment by hiimtmac** [comment]
> @hiimtmac As far as I can see you are using it with NIO2, so it means that with Vapor 4 - is it correct?

Yes correct, but I'm not using the fluent parts at all. Im using SwifQL to just generate raw SQL which I then send to the `req.db.raw(query).all(decoding: CustomModel.self)`

It seems to be in the sql generation part that it falls down (no vapor in the test repo and same problem)
