### ISSUE TITLE
Unable to compile with Xcode 11.4.1 and Swift 5.2.2

### ISSUE THREAD

**Issue by nysander** [SwifQL/SwifQL#29]
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.2 compiler: .../Build/Products/Debug/Fluent.swiftmodule/x86_64-apple-macos.swiftmodule

line 11 of SwifQLTableAlias.swift - I use version compatible with Vapor 3 - 0.28.0 (and for now I am not able to upgrade to Vapor 4)

```
//
//  SwifQLTableAlias.swift
//  SwifQL
//
//  Created by Mihael Isaev on 11/11/2018.
//

import Foundation

#if canImport(Fluent)
import Fluent <------ HERE 
#endif
```

**Comment by MihaelIsaev** [comment]
Hey, it looks like build cache issue. Have you tried to remove `.build` folder and clean both `XcodeBuild` and `DerivedData`?

**Comment by nysander** [comment]
this resolved issue, but only when opened project from Package.swift, not the one generated via vapor tool
